### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by RandomLegend** [megastruktur/foundryvtt-place-gpt#1]
Hey, nice addon!

Would be helpful to have a setting to tell ChatGPT what language to use when generating.

If you take a look at https://foundryvtt.com/packages/ai-description-generator you can see that you can set your own language in the settings.

Have a nice day!

**Comment by megastruktur** [comment]
Hey, thanks for your feedback  :)
I know how to do better. I will tell the AI to answer on the language of request. I've already have the similar system working, however it needs some tweaks.
So, let's look forward. I think it will take a day or two and I'll deploy a new version and reply here  :)
